### ISSUE TITLE
Missing code?

### ISSUE THREAD

**Issue by ryanpoplin** [shorttompkins/benm#12]
Is it implied that I'm to add Updating and Deletion functionalities in this example? I'm not seeing the code in the repo, or the the options after it's being served locally in the views and templates...

BTW awesome guide!

**Comment by shorttompkins** [comment]
Hey,  Yes it is somewhat implied that the project is not 100% complete but more of a starting point.  I will leave this issue open though as I will be adding stuff for server-side testing and I should add update and delete methods as well for the Contacts.  Thanks!!

**Comment by ryanpoplin** [comment]
Awesome! You're the man.

**Comment by shorttompkins** [comment]
Hey I just updated the repo to include server side testing for node as well as delete functionality for the app.  I didnt add support for updating as thats a bit more complicated (because it requires adding a new layer to the front end app).  I will be adding this eventually, but wanted to close this issue for now.  Please refer to the README for updated instructions for testing.  This update will require running npm install because of some added dependencies (mocha, chai, sinon, proxyquite, etc).

**Comment by ryanpoplin** [comment]
Sweet!
